# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       python: 3.11
#     commands:
#       - pip install --upgrade pip
#       - pip install -r requirements.txt
#       - pip install pylint
#       # Add any other pre-build commands here

#   post_build:
#     commands:
#       - python --version
#       - pylint $CODEBUILD_SRC_DIR/*.py
#       - pylint $CODEBUILD_SRC_DIR/library/*.py

# artifacts:
#   files:
#     - '**/*'

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # Install necessary dependencies (adjust as needed)
      - sudo yum update -y
      - sudo yum install -y curl jq python3-pip --allowerasing
      
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pylint
      - echo "Installing corretto (OpenJDK) version 21 ..."
      - export JAVA_HOME="$JAVA_21_HOME"
      - export JDK_HOME="$JDK_21_HOME"
      - for tool_path in "$JAVA_HOME"/bin/*
      - export GRADLE_VERSION=$GRADLE_85_VERSION
      - unlink /usr/bin/gradle
      - ln -s /usr/local/gradle-$GRADLE_85_VERSION/bin/gradle /usr/bin/gradle
      - yum update -y
      - yum install -y jq
      - retry_count=3
      - for i in $(seq 1 $retry_count); do wget https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz && break || sleep 10; done
      - tar xzf apache-maven-3.5.4-bin.tar.gz || true
      - ln -s apache-maven-3.5.4 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - mvn sonar:sonar -Dsonar.login=58d27d02c7dba8aa6e7568e6ac85d93b5946741b -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=24devopsproject -Dsonar.organization=PDDeshmukh116 || true
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=24devopsproject >result.json
      # Set retry count variable
      - retry_count=3
      - cat result.json

  build:
    commands:
      # Run pylint
      - pylint $CODEBUILD_SRC_DIR/*.py
      - pylint $CODEBUILD_SRC_DIR/library/*.py

  post_build:
    commands:
      # Your post-build commands here

artifacts:
  files:
    - '**/*'


